// schemas/sponsor.ts
export default {
    name: 'sponsor',
    type: 'document',
    title: 'Sponsor',
    fields: [
        {
            name: "slug",
            type: "string",
            title: "Slug",
            description: "The end of this sponsor's web address, e.g. \"twigg\". Lowercase, hyphenated, no spaces.",
            validation: (Rule: any) => Rule.required()
        },
        {
            name: 'name',
            type: 'string',
            title: 'Name',
            validation: (Rule: any) => Rule.required()
        },
        {
            name: 'tier',
            type: 'string',
            title: 'Tier',
            description: "Optional sponsorship level, used to group/rank sponsors on the site.",
            options: {
                list: [
                    { title: "Headline", value: "headline" },
                    { title: "Gold", value: "gold" },
                    { title: "Silver", value: "silver" },
                    { title: "Bronze", value: "bronze" },
                    { title: "Supporter", value: "supporter" }
                ]
            }
        },
        {
            name: 'featured',
            type: 'boolean',
            title: 'Featured',
            initialValue: false
        },
        {
            name: 'url',
            type: 'url',
            title: 'URL'
        },
        {
            name: 'logo',
            type: 'image',
            title: 'Logo',
            description: "The logo exactly as the sponsor supplied it. Upload it here even if it has white space around it — the site crops its own copy."
        },
        {
            name: 'logoTrimmed',
            type: 'image',
            title: 'Logo (cropped for the site)',
            description: "Generated by `pnpm trim-logos` — don't edit this. It's the logo cropped tight to the artwork so every sponsor sits at the same visual weight in the logo wall. Replace the logo above and run the command again to refresh it.",
            readOnly: true
        },
        {
            /* Lets `pnpm trim-logos` tell a stale crop from an up-to-date one
               without re-processing every sponsor on every run. */
            name: 'logoTrimmedFrom',
            type: 'string',
            title: 'Cropped from',
            readOnly: true,
            hidden: true
        },
        {
            name: 'description',
            type: 'text',
            title: 'Description'
        },
        {
            name: 'address',
            type: 'string',
            title: 'Address'
        },
        {
            name: 'testimonial',
            type: 'text',
            title: 'Testimonial'
        }
    ],
    orderings: [
        {
            title: "Name (A–Z)",
            name: "nameAsc",
            by: [{ field: "name", direction: "asc" }]
        }
    ],
    preview: {
        select: { title: "name", subtitle: "tier", media: "logo" }
    }
}
